"""test change type

Revision ID: 414eaf480909
Revises: def5506f3e85
Create Date: 2025-04-18 19:34:04.599917

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "414eaf480909"
down_revision: Union[str, None] = "def5506f3e85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("age", sa.Integer(), nullable=False))
    op.alter_column(
        "user",
        "id",
        existing_type=mysql.INTEGER(),
        type_=sa.String(length=38),
        existing_nullable=False,
    )
    op.drop_index("email", table_name="user")
    op.create_unique_constraint(None, "user", ["age"])
    op.drop_column("user", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", mysql.VARCHAR(length=100), nullable=False))
    op.create_index("email", "user", ["email"], unique=True)
    op.alter_column(
        "user",
        "id",
        existing_type=sa.String(length=38),
        type_=mysql.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("user", "age")
    # ### end Alembic commands ###
