"""nullify age

Revision ID: c44e20976c90
Revises: 414eaf480909
Create Date: 2025-04-18 20:32:06.890402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c44e20976c90'
down_revision: Union[str, None] = '414eaf480909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'age',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('age', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('age', 'user', ['age'], unique=True)
    op.alter_column('user', 'age',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
